## Naive Bayes Algorithm
The Naive Bayes algorithm is a type of supervised learning algorithm that is based on Bayes'
theorem. It is a probabilistic classifier that uses Bayes' theorem to calculate the probability of a class label given the features of an instance.
The Naive Bayes algorithm is a simple and effective algorithm for classification problems. It is based on
the assumption that the features of an instance are independent of each other, which is not always true in
real-world data.
The Naive Bayes algorithm can be used for both binary and multi-class classification problems. For binary
classification problems, it can be used to classify instances into one of two classes. For multi-class classification
problems, it can be used to classify instances into one of multiple classes.
## Bayes Theorem
Bayes' theorem is a mathematical formula that describes the probability of a hypothesis given some evidence. It
is used in the Naive Bayes algorithm to calculate the probability of a class label given the features
of an instance. The formula for Bayes' theorem is:
P(H|E) = P(E|H) \* P(H) / P(E)

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [2]:
# load the dataset
iris = load_iris()
X = iris.data
y = iris.target

# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)

In [3]:
# model initialize
gnb = GaussianNB()

# train the model
gnb.fit(X_train, y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy Score:  0.9333333333333333
Confusion Matrix: 
 [[ 8  0  0]
 [ 0  8  0]
 [ 0  2 12]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.80      1.00      0.89         8
           2       1.00      0.86      0.92        14

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30

