In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [2]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [4]:
# create a 2x3 matrix
d = np.array([[1,2,3], [4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# create a matrix of big dimension
e = np.arange(0, 50, 2).reshape(5,5)
e

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [7]:
# slicing a matrix
e[0:3, 1:3]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [8]:
e.min(axis=1)

array([ 0, 10, 20, 30, 40])

In [9]:
f = e[0:3, 1:3]
f

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [10]:
f + np.array([10,12])

array([[12, 16],
       [22, 26],
       [32, 36]])

In [11]:
f * np.array([10,12])

array([[ 20,  48],
       [120, 168],
       [220, 288]])

In [13]:
np.vstack((f, np.array([10,12])))

array([[ 2,  4],
       [12, 14],
       [22, 24],
       [10, 12]])

In [14]:
f

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [16]:
np.flip(f)

array([[24, 22],
       [14, 12],
       [ 4,  2]])