In [3]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
a2 = a[np.newaxis, :]
print(a2)
print(a2.ndim)

[[0 1 2 3 4 5 6 7 8 9]]
2


In [5]:
a3 = a[:, np.newaxis]
print(a3)
print(a3.ndim)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
2


## Creating arrays with numpy

In [6]:
b = np.array([1, 2, 3, 4, 5, 6, 7])
c = np.array([(1, 2, 3, 4, 5, 6, 7), (12, 13, 14, 15, 16, 17, 18)])
print(b)
print(c)

[1 2 3 4 5 6 7]
[[ 1  2  3  4  5  6  7]
 [12 13 14 15 16 17 18]]


In [7]:
b.shape

(7,)

In [8]:
c.shape

(2, 7)

In [9]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
full = np.full((2,5), 8)
full

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [12]:
print(b)
print(b.shape)
print(len(b))
print(b.size)

[1 2 3 4 5 6 7]
(7,)
7
7


In [13]:
print(c)
print(c.shape)
print(len(c))
print(c.size)

[[ 1  2  3  4  5  6  7]
 [12 13 14 15 16 17 18]]
(2, 7)
2
14


In [14]:
sum = b + c
sum

array([[ 2,  4,  6,  8, 10, 12, 14],
       [13, 15, 17, 19, 21, 23, 25]])

In [15]:
sum2= np.add(b, c)
sum2

array([[ 2,  4,  6,  8, 10, 12, 14],
       [13, 15, 17, 19, 21, 23, 25]])

In [18]:
# empty array
np.empty(3)
print(np.empty((2,3)))

[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
 [1.69119873e-306 1.24611673e-306 1.11262266e-307]]


In [19]:
# arange
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [20]:
lin = np.linspace(0, 10, num=9)
lin

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [21]:
# define dtype of array
x = np.arange(22.6, dtype=np.float64)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])

In [22]:
ind = np.argsort(x, axis=0)
ind

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22], dtype=int64)

In [23]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = np.concatenate((arr1, arr2))
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# concatenate array
x = np.array([[1,2], [3,4]]) # 2x2
y = np.array([[6,7]])        # 1x2

In [27]:
z = np.concatenate((x,y))
z


array([[1, 2],
       [3, 4],
       [6, 7]])

In [29]:
x1 = np.array([[3,2], [4,5]])
x2 = np.array([[7,8], [9,10]])
x3 = np.concatenate((x1,x2))
print(x1)
print(x2)
print(x3)

[[3 2]
 [4 5]]
[[ 7  8]
 [ 9 10]]
[[ 3  2]
 [ 4  5]
 [ 7  8]
 [ 9 10]]


In [30]:
x4 = np.concatenate((x1,x2))
print(x4)

[[ 3  2]
 [ 4  5]
 [ 7  8]
 [ 9 10]]


In [32]:
# creating a 3D array
arr_3d = np.array([[[0,1,2,3],
                    [4,5,6,7],
                    [8,9,10,11],
                    [12, 13, 14, 15]]])
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [33]:
arr_3d.shape

(1, 4, 4)

In [34]:
arr_3d1 = np.array([[[0,1,2,3]],
                    [[4,5,6,7]],
                    [[8,9,10,11]],
                    [[12, 13, 14, 15]]]
                    )
arr_3d1.shape

(4, 1, 4)